version: '3.8'

services:
  # Redis服务 - 我们的数据存储
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - rate-limiter-network

  # 我们即将构建的API服务（先注释掉）
  # api:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: rate-limiter-api
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Redis__ConnectionString=redis:6379
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - rate-limiter-network

volumes:
  redis-data:

networks:
  rate-limiter-network:
    driver: bridge